server:
  port: 8847
spring:
  mail:
    host: smtp.163.com
    username: /**
    password: 123123
    protocol: smtp

app:
  default-email-sender: /**
  userlist:
    - host: baidu.com
      email: 123@qq.com
    - host: taobao.cn
      email: 123@qq.com

timePlan:
  scheduler: " 0/10 * * * * ? "